//! MySQL. MariaDB parte de estas mismas listas (dialects/mariadb.rs).

use super::{DoBlocks, EngineDefinition, InsertDefaults, RoutineBodies};

pub const DEFINITION: EngineDefinition = EngineDefinition {
    id: "mysql",
    parser: || Box::new(sqlparser::dialect::MySqlDialect {}),
    statement_starters: STARTERS,
    unparsed_syntax: &[UNPARSED],
    unparsed_writes: UNPARSED_WRITES,
    system_tables: &["DUAL"],
    system_table_prefixes: &[],
    folds_unquoted_to_lowercase: false,
    backslash_escapes: true,
    identifier_quote: '`',
    insert_defaults: InsertDefaults::EmptyValues,
    executable_comments: &["/*!"],
    routine_kinds: ROUTINE_KINDS,
    routine_bodies: RoutineBodies::Block,
    do_blocks: DoBlocks::Expression,
    select_into_variable_lists: true,
    sql_mode_query: Some(SQL_MODE_QUERY),
    lines: include_str!("../../../../support/mysql.json"),
};

pub(super) const ROUTINE_KINDS: &[&str] = &["PROCEDURE", "FUNCTION", "TRIGGER", "EVENT"];
pub(super) const SQL_MODE_QUERY: &str = "SELECT @@SESSION.sql_mode";

pub(super) const UNPARSED_WRITES: &[&[&str]] = &[
    &["DROP", "EVENT"],
    &["ALTER", "EVENT"],
    &["ALTER", "PROCEDURE"],
    &["ALTER", "FUNCTION"],
    &["GRANT", "EXECUTE"],
    &["REVOKE", "EXECUTE"],
    &["OPTIMIZE", "TABLE"],
    &["CHECK", "TABLE"],
    &["REPAIR", "TABLE"],
    &["DO"],
    &["HELP"],
];

pub(super) const STARTERS: &[&str] = &[
    "SELECT",
    "WITH",
    "INSERT",
    "REPLACE",
    "UPDATE",
    "DELETE",
    "CREATE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "RENAME",
    "SET",
    "SHOW",
    "USE",
    "LOAD",
    "PREPARE",
    "EXECUTE",
    "DEALLOCATE",
    "GRANT",
    "REVOKE",
    "CALL",
    "DO",
    "LOCK",
    "UNLOCK",
    "FLUSH",
    "OPTIMIZE",
    "ANALYZE",
    "CHECK",
    "CHECKSUM",
    "REPAIR",
    "HELP",
    "EXPLAIN",
    "DESCRIBE",
    "DESC",
    "START",
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
    "SAVEPOINT",
    "RELEASE",
    "XA",
    "KILL",
    "RESET",
    "PURGE",
    "TABLE",
    "VALUES",
    "HANDLER",
    "SIGNAL",
    "RESIGNAL",
    "INSTALL",
    "UNINSTALL",
    "CLONE",
    "IMPORT",
];

/// Tambien de MariaDB, que suma lo suyo.
pub(super) const UNPARSED: &[&[&str]] = &[
    // Operadores: `a MOD 2`, `a SOUNDS LIKE 'x'`.
    &["MOD"],
    &["SOUNDS", "LIKE"],
    // Modificadores del SELECT, que el parser toma por una columna.
    &["SQL_CALC_FOUND_ROWS"],
    &["SQL_NO_CACHE"],
    &["SQL_CACHE"],
    &["SQL_BUFFER_RESULT"],
    &["SQL_SMALL_RESULT"],
    &["SQL_BIG_RESULT"],
    &["HIGH_PRIORITY"],
    &["STRAIGHT_JOIN"],
    &["DISTINCTROW"],
    // `BINARY a`: tambien lo lee como una columna.
    &["BINARY"],
    &["WITH", "ROLLUP"],
    &["LOCK", "IN", "SHARE", "MODE"],
    &["INTO", "OUTFILE"],
    &["INTO", "DUMPFILE"],
    &["PREPARE"],
    &["LOAD", "DATA"],
    &["CREATE", "USER"],
    // DDL: modificadores numericos, particiones, opciones de tabla, indices.
    &["DECIMAL", "...", "UNSIGNED"],
    &["DEC", "...", "UNSIGNED"],
    &["NUMERIC", "...", "UNSIGNED"],
    &["FLOAT", "...", "UNSIGNED"],
    &["DOUBLE", "...", "UNSIGNED"],
    &["REAL", "...", "UNSIGNED"],
    &["ZEROFILL"],
    &["PARTITION", "BY", "RANGE"],
    &["PARTITION", "BY", "LIST"],
    &["PARTITION", "BY", "HASH"],
    &["PARTITION", "BY", "KEY"],
    &["PARTITION", "BY", "LINEAR"],
    &["ALTER", "TABLE", "...", "ENGINE"],
    &["ALTER", "TABLE", "...", "AUTO_INCREMENT"],
    &["ALTER", "TABLE", "...", "ROW_FORMAT"],
    &["ALTER", "TABLE", "...", "CHARSET"],
    &["DROP", "INDEX"],
    &["DROP", "KEY"],
    &["DROP", "FOREIGN", "KEY"],
    &["DROP", "PRIMARY", "KEY"],
    &["CREATE", "FULLTEXT"],
    &["CREATE", "SPATIAL"],
    &["CHECK", "OPTION"],
    // Sentencias de sesion y administracion.
    &["WITH", "CONSISTENT", "SNAPSHOT"],
    &["SET", "...", ":="],
    &["EXPLAIN", "FORMAT"],
    &["FULL", "PROCESSLIST"],
    &["LOCK", "TABLES"],
    &["UNLOCK", "TABLES"],
    // UPDATE de una tabla con ORDER BY o LIMIT.
    &["UPDATE", "...", "ORDER", "BY"],
    &["UPDATE", "...", "LIMIT"],
];
