//! PostgreSQL.

use super::{DoBlocks, EngineDefinition, InsertDefaults, RoutineBodies};

pub const DEFINITION: EngineDefinition = EngineDefinition {
    id: "postgres",
    parser: || Box::new(sqlparser::dialect::PostgreSqlDialect {}),
    statement_starters: STARTERS,
    unparsed_syntax: &[UNPARSED],
    unparsed_writes: UNPARSED_WRITES,
    system_tables: &[],
    // pg_catalog esta siempre en el search_path.
    system_table_prefixes: &["pg_"],
    folds_unquoted_to_lowercase: true,
    // Con standard_conforming_strings (lo predeterminado), `\` es un caracter mas.
    backslash_escapes: false,
    identifier_quote: '"',
    insert_defaults: InsertDefaults::DefaultValues,
    executable_comments: &[],
    routine_kinds: &["PROCEDURE", "FUNCTION", "TRIGGER"],
    routine_bodies: RoutineBodies::Quoted,
    do_blocks: DoBlocks::Anonymous,
    select_into_variable_lists: false,
    sql_mode_query: None,
};

const UNPARSED_WRITES: &[&[&str]] = &[
    &["ALTER", "FUNCTION"],
    &["ALTER", "PROCEDURE"],
    &["ALTER", "ROUTINE"],
    &["GRANT", "EXECUTE"],
    &["REVOKE", "EXECUTE"],
    &["CREATE", "RULE"],
    &["CREATE", "AGGREGATE"],
    &["CREATE", "OPERATOR"],
    &["DO"],
    &["COMMENT", "ON", "FUNCTION"],
    &["COMMENT", "ON", "PROCEDURE"],
    &["COMMENT", "ON", "ROUTINE"],
    &["COMMENT", "ON", "TRIGGER"],
    &["CREATE", "OR", "REPLACE", "RULE"],
];

const STARTERS: &[&str] = &[
    "SELECT",
    "WITH",
    "INSERT",
    "UPDATE",
    "DELETE",
    "MERGE",
    "CREATE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "SET",
    "RESET",
    "SHOW",
    "USE",
    "COPY",
    "PREPARE",
    "EXECUTE",
    "DEALLOCATE",
    "GRANT",
    "REVOKE",
    "CALL",
    "DO",
    "LOCK",
    "VACUUM",
    "ANALYZE",
    "CLUSTER",
    "REINDEX",
    "REFRESH",
    "EXPLAIN",
    "BEGIN",
    "START",
    "COMMIT",
    "END",
    "ROLLBACK",
    "SAVEPOINT",
    "RELEASE",
    "DECLARE",
    "FETCH",
    "MOVE",
    "CLOSE",
    "LISTEN",
    "NOTIFY",
    "UNLISTEN",
    "COMMENT",
    "SECURITY",
    "DISCARD",
    "CHECKPOINT",
    "IMPORT",
    "TABLE",
    "VALUES",
];

const UNPARSED: &[&[&str]] = &[
    &["CREATE", "DOMAIN"],
    &["CREATE", "EXTENSION"],
    &["CREATE", "POLICY"],
    &["CREATE", "SEQUENCE"],
    &["CREATE", "UNLOGGED"],
    &["INCLUDING"],
    &["EXCLUDING"],
    &["NOT", "VALID"],
    &["VALIDATE", "CONSTRAINT"],
    &["CHECK", "OPTION"],
    &["WITH", "DATA"],
    &["OVERRIDING", "SYSTEM", "VALUE"],
    &["OVERRIDING", "USER", "VALUE"],
    // Tablas hijas: sqlparser no reconoce PARTITION OF.
    &["PARTITION", "OF"],
    &["WITH", "NO", "DATA"],
    &["FOR", "NO", "KEY", "UPDATE"],
    &["FOR", "KEY", "SHARE"],
    &["BETWEEN", "SYMMETRIC"],
];
