-- JSON_TABLE.
SELECT * FROM JSON_TABLE('[1,2]', '$[*]' COLUMNS (a INT PATH '$')) AS jt
-- ---
-- OFFSET ... FETCH.
SELECT a FROM (SELECT 1 AS a) t ORDER BY a OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY
-- ---
-- SKIP LOCKED.
SELECT 1 FROM DUAL FOR UPDATE SKIP LOCKED
