[package]
name = "khipu-driver-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
khipu-driver-core.workspace = true
khipu-engine.workspace = true
sqlx = { workspace = true, features = ["postgres"] }
async-trait.workspace = true
futures-util.workspace = true

[dev-dependencies]
tokio.workspace = true
